### PR TITLE
Add a note on legacy openssl support

### PR DESCRIPTION
**Pull request by pereriksson**
Hope this will help other developers experiencing the same problem as I did.

### CODE REVIEW

**Comment by pereriksson** [comment]
Is it possible to get this merged? :-)

**Comment by pereriksson** [comment]
@pmmmwh Maybe we can provide both options to the developer? Maybe some are uncomfortable with modifying the certs they have received that are used for important stuff :-)

**Comment by pmmmwh** [comment]
> @pmmmwh Maybe we can provide both options to the developer? Maybe some are uncomfortable with modifying the certs they have received that are used for important stuff :-)

IMO we should encourage the "proper" way since OpenSSL 1.1.1 will be EoL in late September this year - and for core security software I find the "re-encryption" approach more desirable - but I agree we can provide both options in case some people are stuck. I will try to write up something that highlights this nuance in the README today.

**Comment by pereriksson** [comment]
> IMO we should encourage the "proper" way since OpenSSL 1.1.1 will be EoL in late September this year - and for core security software I find the "re-encryption" approach more desirable - but I agree we can suggest both solutions in case some people are stuck. I will try to write up something that highlights this nuance in the README today.

Great, do we need to worry about different platforms here?

**Comment by eliasnorrby** [comment]
For anyone trying the [re-encryption approach](https://github.com/anyfin/bankid/pull/61#issuecomment-1671560111), I had troubles reading from stdin using OpenSSL version 3.1.2.

```bash
openssl pkcs12 -in old.pfx -nodes -legacy | openssl pkcs12 -export -out new.pfx
# failing with
Could not read any certificates from -in file from <stdin>
```

As a workaround, I did:

```bash
openssl pkcs12 -in old.pfx -nodes -legacy -out combined.pem
openssl pkcs12 -in combined.pem -export -out new.pfx
```

**Comment by pmmmwh** [comment]
> Great, do we need to worry about different platforms here regarding re-encryption?

Nope, as long as you are using OpenSSL v3+ it should be good.

**Pull request closed without merging**
